/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * about_company.java
 *
 * Created on 30 Jun, 2015, 9:57:23 PM
 */

package jobportal;

/**
 *
 * @author abhilasha
 */
import java.sql.*;
import javax.swing.*;
public class about_company extends javax.swing.JFrame {
String email;
Connection conn;
Statement stmt;
ResultSet rs;
String text="";
int c=0,s=0;
    /** Creates new form about_company */
    public about_company(String email_id) {
        initComponents();
        setSize(740,620);
        setResizable(false);
        email=email_id;
        jButton2.setVisible(false);
       jTextArea1.setEditable(true);
          try
         {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            conn=DriverManager.getConnection("jdbc:odbc:seeker");
            System.out.println("connected");
            stmt=conn.createStatement();
            rs=stmt.executeQuery("select * from company");
         while(rs.next())
         {
            
          String em=rs.getString("email_id");
          if(email.equals(em))
          {
              c=1;
                jTextArea1.setEditable(false);
              text=rs.getString("about_comp");
jTextArea1.setText(text);
jButton2.setVisible(true);
jButton1.setVisible(false);
s=rs.getInt("ID");
          }
         }
    }
                  catch(SQLException se)
     {
         System.out.println(se);
     }
catch(ClassNotFoundException ce)
{
    System.out.println(ce);
}
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jLabel1.setText("About our Company:-");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 10, 400, 56);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 90, 650, 420);

        jButton1.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(210, 521, 130, 40);

        jButton2.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(380, 520, 120, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abc/apple-company-logo-wallpaper.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 740, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String abt_company=jTextArea1.getText();
        try
         {
            jTextArea1.setEditable(true);
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            conn=DriverManager.getConnection("jdbc:odbc:seeker");
            System.out.println("connected");
            stmt=conn.createStatement();
            if(c==1)
            {
                stmt.executeUpdate("update company set about_comp="+"'"+abt_company+"'"+" where ID="+s);
            }
     if(c==0)
     {
         jTextArea1.setEditable(true);
       if(abt_company.equals(""))
{
    JOptionPane.showMessageDialog(null,"Enter detail");
}
else
{
     
            stmt.executeUpdate("insert into company(email_id,about_comp) values('"+email+"','"+abt_company+"')");

     }
     }
        }
            catch(SQLException se)
     {
         System.out.println(se);
     }
catch(ClassNotFoundException ce)
{
    System.out.println(ce);
}

     // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   jTextArea1.setEditable(true);
   jButton1.setVisible(true);


             // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new about_company("ab").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
