/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * calls.java
 *
 * Created on 6 Jul, 2015, 6:17:06 PM
 */

package jobportal;

/**
 *
 * @author abhilasha
 */
import java.sql.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
public class calls extends javax.swing.JFrame implements ActionListener {
String email;
ResultSet rs,rs1,rs2;
Connection conn;
Statement stmt,stmt1,stmt2;
String c_id[]=new String[1000];
String j_id[]=new String[1000];
String text[]=new String[1000];
String comp_name[]=new String[1000];
String designation[]=new String[1000];
String arr[][]=new String[1000][1000];
JPanel p=new JPanel();
JButton b[]=new JButton[1000];
JPanel p1[]=new JPanel[1000];
JPanel p2[]=new JPanel[1000];
JScrollPane sp=new JScrollPane(p);
int c=0;
    /** Creates new form calls */
    public calls(String a) {
        initComponents();
        email=a;
        setLayout(new GridLayout(1,1));
p.setLayout(new GridLayout(1000,1));
       try
         {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            conn=DriverManager.getConnection("jdbc:odbc:seeker");
            System.out.println("connected");

            stmt=conn.createStatement();
            rs=stmt.executeQuery("select * from interview");
            while(rs.next())
            {
                String employee_id=rs.getString("email_id");
                if(employee_id.equals(email))
                {
                c_id[c]=rs.getString("comp_id");
                System.out.println(c_id[c]);
                j_id[c]=rs.getString("job_id");
                   System.out.println(j_id[c]);
                text[c]=rs.getString("letter");
                    System.out.println(text[c]);
                     System.out.println("abc");
                    stmt1=conn.createStatement();
                  rs1=stmt1.executeQuery("select * from employer");
               
                  while(rs1.next())
                  { 
                      String str=rs1.getString("email");
                      System.out.println(str);
                      if(str.equals(c_id[c]))
                      {
                       comp_name[c]=rs1.getString("comp_name");
                         System.out.println(comp_name[c]);
                  }
                  
                  }
                  stmt2=conn.createStatement();
                  rs2=stmt1.executeQuery("select * from job");
                  while(rs2.next())
                  {
                      String str1=rs2.getString("job_id");
                      if(str1.equals(j_id[c]))
                      {
                          designation[c]=rs2.getString("designation");
                      }

                  }




                   c++;
                }
        

            }
for(int i=0;i<c;i++)
{
    arr[i][0]=comp_name[i];
   
    arr[i][1]=designation[i];
   // arr[i][1]=text[i];
}
              for(int i=0;i<c;i++)
           {
     for(int j=0;j<=1;j++)

               {

                      System.out.println(arr[i][j]);



          }}
   for(int i=0;i<c;i++)
           {
           p1[i]=new JPanel();
           p2[i]=new JPanel();

         // p[i].setBackground(Color.white);
           p1[i].setLayout(new GridLayout(1,2));
           JLabel l=new JLabel(c+"         InterView Call from      "+arr[i][0]+"     for    "+arr[i][1]);
l.setFont(new Font("arial",Font.BOLD,14));
                       p1[i].add(l);



          
        b[i]=    new JButton("View");
        p2[i].setLayout(new FlowLayout());
       p2[i].add(b[i]);
            p1[i].add(p2[i]);
       // p1[i].add(b[i]);
            p.add(p1[i]);
          
       add(sp);

       }
       }
       catch(SQLException se)
       {
           System.out.println(se);
       }
        catch(ClassNotFoundException ce)
        {
            System.out.println(ce);
        }
for(int i=0;i<c;i++)
b[i].addActionListener(this);
    }

    public void actionPerformed(ActionEvent ae)
    {
        for(int i=0;i<c;i++)
        {


        if(ae.getSource()==b[i])
        {
new view_call(text[i]).setVisible(true);
        }
    }}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calls("abcd355").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
