/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * interview_call.java
 *
 * Created on 6 Jul, 2015, 1:30:14 PM
 */

package jobportal;

/**
 *
 * @author abhilasha
 */
import java.sql.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
public class interview_call extends javax.swing.JFrame implements ActionListener {
String email,j_id;
Connection conn;
Statement stmt,stmt1;
ResultSet rs;
ResultSet rs1;
ResultSet rs2;
String str1,company_id;
int s=0,c=0;
JTextArea jTextArea1=new JTextArea();
 JButton b1=new JButton("Send");
  JButton b2=new JButton("Edit");
    /** Creates new form interview_call */
    public interview_call(String a,String b,String d) {
        initComponents();
        email=a;
        j_id=b;
        company_id=d;
       b2.setVisible(false);
       JPanel p1=new JPanel();
       p1.setLayout(new FlowLayout());
       JLabel l1=new JLabel("Interview Call",JLabel.CENTER);
      
       l1.setFont(new Font("arial",Font.BOLD,24));
        b1.setFont(new Font("arial",Font.BOLD,24));
        b2.setFont(new Font("arial",Font.BOLD,24));
        p1.add(b1);
        p1.add(b2);
        JScrollPane sp=new JScrollPane(jTextArea1);
        setLayout(new BorderLayout());
        add(sp,BorderLayout.CENTER);
        add(l1,BorderLayout.NORTH);
          add(p1,BorderLayout.SOUTH);
          b1.addActionListener(this);

             b2.addActionListener(this);

                       try
                {

            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            conn=DriverManager.getConnection("jdbc:odbc:seeker");
            System.out.println("connected");
            stmt=conn.createStatement();
            String text=jTextArea1.getText();
           rs=stmt.executeQuery("select * from interview");
           while(rs.next())
           {
            String str=rs.getString("email_id");
           String str2=rs.getString("job_id");

            if(str.equals(email)&&str2.equals(j_id))
            {

              str1=rs.getString("letter");

              if(str1.equals(""))
              {
                  c=0;
              }
              else c=1;

              if(c==1)

              {
                  jTextArea1.setEditable(false);
                  b2.setVisible(true);
                  b1.setEnabled(false);
                  jTextArea1.setText(str1);
              }
           }
           }




            }
                   catch(SQLException se)
     {
     System.out.println(se);

    }
     catch(ClassNotFoundException ce)
     {
         System.out.println(ce);

        }



    }

    public void actionPerformed(ActionEvent ae)
    {
        if(ae.getSource()==b1)
        {
                        try
                {
                             String text=jTextArea1.getText();


            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            conn=DriverManager.getConnection("jdbc:odbc:seeker");
            System.out.println("connected");
            stmt=conn.createStatement();
           System.out.println("abcd");
//stmt.executeUpdate("delete * from interview");
       stmt.executeUpdate("insert into interview(email_id,job_id,letter,comp_id) values('"+email+"','"+j_id+"','"+text+"','"+company_id+"')");
            b1.setEnabled(false);
                        }

                   catch(SQLException se)
     {
     System.out.println(se);

    }
     catch(ClassNotFoundException ce)
     {
         System.out.println(ce);

        }
 setVisible(false);
        }
       if(ae.getSource()==b2)
       {
           jTextArea1.setEditable(true);
           b1.setEnabled(true);
       }

    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 687, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interview_call("abcd","567","abcd").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
