package jobportal;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jobs_matching.java
 *
 * Created on 29 Jun, 2015, 5:13:25 PM
 */

/**
 *
 * @author abhilasha
 */
import java.sql.*;
import javax.swing.*;

import java.awt.*;

public class jobs_matching extends javax.swing.JFrame {

    Connection conn;
    Statement stmt;
    ResultSet rs;
    ResultSet rs1;
    String email;
   int c=0;
  
    /** Creates new form jobs_matching */
    public jobs_matching(String a) {
        initComponents();
        
       email=a;
       String qual="";
       String exp_m="";
      String exp_y="";
      String qua;
      String expm;
      String expy;
      String desig[]=new String[100];
      String company[]=new String[100];
      String place[]=new String[100];
     String expr[]=new String[100];
     String salary[]=new String[100];
     String date[]=new String[100];
     String detail[]=new String[100];
     String apply[]=new String[100];
     String arr[][]=new String[100][100];

     String column[]={"Designation","Company","Location","expr","Salary","Date"};
     try
         {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            conn=DriverManager.getConnection("jdbc:odbc:seeker");
            System.out.println("connected");
            stmt=conn.createStatement();
           rs=stmt.executeQuery("select * from employee");
           while(rs.next())

     {
         String str=rs.getString("email_id");
         if(str.equals(email))
         {
qual=rs.getString("qualifications");
exp_m=rs.getString("exp_mnths");
exp_y=rs.getString("exp_year");

         }
           }
          
    
         
     rs1=stmt.executeQuery("select * from job");
       
            while(rs1.next())
            {
              qua=rs1.getString("qualifications");
              expm=rs1.getString("exp_mnths");
              expy=rs1.getString("exp_year");
         if(qua.equals(qual)&&exp_m.equals(expm)&&exp_y.equals(expy))
         {
             desig[c]=rs1.getString("designation");
             company[c]=rs1.getString("job_industry");
             place[c]=rs1.getString("place");
            expr[c]=expy;
             
             salary[c]=rs1.getString("salary");
             date[c]=rs1.getString("date_of");
             
            c++;
              
            }
              System.out.println(c);
           }
        
   
           stmt.close();
           conn.close();
           
   /* for(int i=0;i<c;i++)
     {
         System.out.println(desig[i]+"\t\t"+company[i]+"\t\t"+place[i]+"\t\t"+expr[i]+"\t\t"+salary[i]+"\t\t"+date[i]);
    }*/

      for(int i=0;i<c;i++)
      {
              arr[i][0]=desig[i];
              arr[i][1]=company[i];
              arr[i][2]=place[i];
              arr[i][3]=expr[i]+" year";
              arr[i][4]="Rs."+salary[i];
              arr[i][5]=date[i];
      }
           for(int i=0;i<c;i++)
           {
               for(int j=0;j<=5;j++)
               {
                   System.out.print(arr[i][j]+"\t\t");
           }
System.out.println();
           }

        jPanel1.setLayout(new GridLayout(1,1));
       JTable table=new JTable(arr,column);
JButton b=new JButton("abc");

       table.setRowHeight(30);
      
      // table.setRowMargin(500);
       jPanel1.add(table);
       jPanel1.add(new JScrollPane(table),BorderLayout.CENTER);

     }
     catch(SQLException se)
     {
     System.out.println(se);

    }
     catch(ClassNotFoundException ce)
     {
         System.out.println(ce);
     }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel1.setText("Jobs matching your profile:-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 446, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jobs_matching("abcd").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
