/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * view_feedback.java
 *
 * Created on 8 Jul, 2015, 2:05:40 PM
 */

package jobportal;

/**
 *
 * @author abhilasha
 */import java.sql.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.io.*;
public class view_feedback extends javax.swing.JFrame implements ActionListener{
Connection conn;
 Statement stmt;
  Statement stmt1;
  Statement stmt2;
 ResultSet rs;
  ResultSet rs1;
   ResultSet rs2;
String email,j_id;
JPanel p1=new JPanel();
JPanel p2=new JPanel();
JPanel p3=new JPanel();
JPanel panel[]=new JPanel[1000];
JPanel panel1[]=new JPanel[1000];
JButton b[]=new JButton[1000];
int c=0,s=0;
String user_id[]=new String[1000];
JScrollPane sp=new JScrollPane(p1);
String message[]=new String[1000];
    /** Creates new form view_feedback */
    public view_feedback() {
        initComponents();
        
                             setLayout(new GridLayout(1,1));
p1.setLayout(new GridLayout(1000,1));

        String column[]={"Subject","Message"};

String user_id[]=new String[1000];
String subject[]=new String[1000];

  String arr[][]=new String[1000][1000];

  p3.setLayout(new FlowLayout());
    JLabel l1=new JLabel("Feedbacks");
    l1.setFont(new Font("arial",Font.BOLD,30));
    p3.add(l1);
    p1.add(p3);

     p2.setLayout(new GridLayout(1,2));
     for(int i=0;i<2;i++)
     {
         JLabel l=new JLabel(column[i]);
         l.setFont(new Font("arial",Font.BOLD,20));
       p2.add(l);
     }
p1.add(p2);
    
     try
         {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            conn=DriverManager.getConnection("jdbc:odbc:seeker");
            System.out.println("connected");
            stmt=conn.createStatement(); 
            rs=stmt.executeQuery("select * from feedback");
            while(rs.next())
            {
                subject[c]=rs.getString("subject");
                message[c]=rs.getString("message");
                c++;
            }
            for(int i=0;i<c;i++)
            {
                arr[i][0]=i+1+". "+subject[i];
                arr[i][1]=message[i];
            }
            
            
             for(int i=0;i<c;i++)
           {
           panel[i]=new JPanel();
            panel1[i]=new JPanel();
           panel[i].setLayout(new GridLayout(1,10));
             panel1[i].setLayout(new FlowLayout());
             


                       panel[i].add(new JLabel(arr[i][0]));



          

           b[i]=    new JButton("View");



            panel1[i].add(b[i]);
            panel[i].add(panel1[i]);


p1.add(panel[i]);
           }
 add(sp);



   
     }
      catch(SQLException se)
     {
     System.out.println(se);

    }
     catch(ClassNotFoundException ce)
     {
         System.out.println(ce);
     }
    for(int i=0;i<c;i++)
    {
        b[i].addActionListener(this);
    }
    
    
    }






    public void actionPerformed(ActionEvent ae)
    {
        for(int i=0;i<c;i++)
        {
            if(ae.getSource()==b[i])
            {
                new detail(message[i]).setVisible(true);
            }
        }
    }




    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view_feedback().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
